# Run this workflow every time a new commit or PR pushed to the repository.
on: [push, pull_request]
# Name of the workflow. If this is blank, it will default to the path of the
# file.
name: Unit Tests
jobs:
  # Name of the job.
  unit-tests:
    # Run the job on these Go versions and operating systems.
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        # os: [ubuntu-latest, macos-latest, windows-latest] # Don't use, spends a lot of cycles.
        os: [ubuntu-latest, windows-latest]
      # Don't cancel all jobs if one fails.
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # Install Go.
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      # Checkout the code.
      - name: Checkout code
        uses: actions/checkout@v2
      # Run all the unit tests.
      - name: Run all unit tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...
      # Install goveralls.
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
    # Send coverage to https://coveralls.io/.
    # - name: Send coverage
    #   env:
    #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: goveralls -coverprofile=covprofile -service=github